#!/usr/bin/env python

# Generated by Rohde&Schwarz Signal Generator SCPI Recorder

# use PyVISA
# 169.254.2.20
from RsInstrument import *
import time
def main():
	InstrObj = RsInstrument('TCPIP::10.66.156.52::hislip0', reset=False, id_query=False,
						options="SelectVisa='rs' , LoggingMode = Off, LoggingToConsole = False")
	# InstrObj.clear()
	InstrObj.read_termination = '\n'
	r1 = 150
	r2 = 20
	v = -10 # m/s
	t_res = 0.1
	t_lenth = abs((r2 - r1))/ abs(v)
    
	InstrObj.write(':SOURce1:AREGenerator:OBJect1:DOPPler:SPEed  %s'%(v*3.6))
	status = InstrObj.query('*OPC?')
	if int(status) != 1:
		return
		
	InstrObj.write(':SOURce1:AREGenerator:OBJect1:RANGe 20')
	status = InstrObj.query('*OPC?')
	if int(status) != 1:
		return
        
	InstrObj.write(':SOURce1:AREGenerator:OBJect1:RCS 30')
	status = InstrObj.query('*OPC?')
	if int(status) != 1:
		return
    
	InstrObj.write(':SOURce1:AREGenerator:OBJect1:STATe 1')
	status = InstrObj.query('*OPC?')
	if int(status) != 1:
		return    

	for i in range(int(t_lenth/t_res)):
		r_now = r1+v*t_res*i
		InstrObj.write(':SOURce1:AREGenerator:OBJect1:RANGe %s' %r_now)
		status = InstrObj.query('*OPC?')
		if int(status) != 1:
			return
		time.sleep(t_res)
	

	InstrObj.write(':SOURce1:AREGenerator:OBJect1:STATe 0')
	status = InstrObj.query('*OPC?')
	if int(status) != 1:
		return    
	InstrObj.close()
	
if __name__ == "__main__":
	main()
